Udemy_MVC_CV/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Udemy_MVC_CV.Models.Entity;

namespace Udemy_MVC_CV.Controllers
{
    [AllowAnonymous]
    public class DefaultController : Controller
    {
        // GET: Default
        DinamikCVEntities db=new DinamikCVEntities();

        public ActionResult Index()
        {
            var degerler=db.TblHakkinda.ToList();
            return View(degerler);
        }

        public PartialViewResult Deneyim()
        {
            var values=db.TblDeneyimlerim.ToList();
            return PartialView(values);
        }

        public PartialViewResult Egitim()
        {
            var values=db.TblEgitim.ToList();
            return PartialView(values);
        }

        public PartialViewResult Yeteneklerim() 
        {
            var values=db.TblYetenek.ToList();
            return PartialView(values);
        }

        public PartialViewResult Hobilerim()
        {
            var values=db.TblHobilerim.ToList();
            return PartialView(values);
        }

        public PartialViewResult Sertifikalarım() 
        {
            var values=db.TblSertifikalarim.ToList();
            return PartialView(values);
        }

        [HttpGet]
        public PartialViewResult iletisim()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult iletisim(TblIletisim iletisim)
        {
            iletisim.Tarih=DateTime.Parse(DateTime.Now.ToShortDateString());
            db.TblIletisim.Add(iletisim);
            db.SaveChanges();
            return PartialView();
        }

    }
}

Udemy_MVC_CV/Controllers/DeneyimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Udemy_MVC_CV.Models.Entity;
using Udemy_MVC_CV.Repositories;

namespace Udemy_MVC_CV.Controllers
{
    public class DeneyimController : Controller
    {
        DeneyimRepository repo=new DeneyimRepository();
        // GET: Deneyim
        public ActionResult Index()
        {
            var deneyimler=repo.List();
            return View(deneyimler);
        }

        [HttpGet]
        public ActionResult DeneyimEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DeneyimEkle(TblDeneyimlerim p)
        {
            if (!ModelState.IsValid)
            {
                return View("DeneyimEkle");
            }
            repo.TAdd(p);
            return RedirectToAction("Index");
        }

        public ActionResult DeneyimSil(int id)
        {
            TblDeneyimlerim t=repo.Find(x=>x.ID==id);
            repo.TDelete(t);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeneyimGetir(int id)
        {
            TblDeneyimlerim t=repo.Find(x=>x.ID==id);
            return View(t);
        }
        
        [HttpPost]
        public ActionResult DeneyimGetir(TblDeneyimlerim p)
        {
            if (!ModelState.IsValid)
            {
                return View("DeneyimGetir");
            }
            TblDeneyimlerim t = repo.Find(x => x.ID == p.ID);
            t.Baslik=p.Baslik;
            t.AltBaslik=p.AltBaslik;
            t.Aciklama=p.Aciklama;
            t.Tarih=p.Tarih;
            repo.TUpdate(t);
            return RedirectToAction("Index");
        }
    }
}

Udemy_MVC_CV/Controllers/EgitimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Udemy_MVC_CV.Models.Entity;
using Udemy_MVC_CV.Repositories;

namespace Udemy_MVC_CV.Controllers
{
    public class EgitimController : Controller
    {
        // GET: Egitim
        EgitimRepository repo=new EgitimRepository();
        public ActionResult Index()
        {
            var degerler = repo.List();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult EgitimEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EgitimEkle(TblEgitim e)
        {
            if (!ModelState.IsValid)
            {
                return View("EgitimEkle");
            }
            repo.TAdd(e);
            return RedirectToAction("Index");
        }

        public ActionResult EgitimSil(int id)
        {
            TblEgitim e = repo.Find(x=>x.ID==id);
            repo.TDelete(e);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EgitimGetir(int id)
        {
            var degerler=repo.Find(x=>x.ID==id);
            return View(degerler);
        }

        [HttpPost]
        public ActionResult EgitimGetir(TblEgitim e)
        {
            if (!ModelState.IsValid)
            {
                return View("EgitimGetir");
            }
            TblEgitim guncel = repo.Find(x => x.ID == e.ID);
            guncel.Baslik=e.Baslik;
            guncel.AltBaslik1 = e.AltBaslik1;
            guncel.AltBaslik2= e.AltBaslik2;
            guncel.GNO=e.GNO;
            guncel.Tarih=e.Tarih;
            repo.TUpdate(guncel);
            return RedirectToAction("Index");
        }
    }
}

Udemy_MVC_CV/Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Udemy_MVC_CV.Repositories;

namespace Udemy_MVC_CV.Controllers
{
    public class IletisimController : Controller
    {
        iletisimRepository repo=new iletisimRepository();
        // GET: Iletisim
        public ActionResult Index()
        {
            var degerler = repo.List();
            return View(degerler);
        }
    }
}

Udemy_MVC_CV/Views/Default/Deneyim.cshtml
@model List<Udemy_MVC_CV.Models.Entity.TblDeneyimlerim>
<div class="resume-section-content">
    <h2 class="mb-5">Deneyimlerim</h2>
    @foreach (var item in Model)
    {
        <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="flex-grow-1">
                <h3 class="mb-0">@item.Baslik</h3>
                <div class="subheading mb-3">@item.AltBaslik</div>
                <p>@item.Aciklama</p>
            </div>
            <div class="flex-shrink-0"><span class="text-primary">@item.Tarih</span></div>
        </div>
    }
</div>

Udemy_MVC_CV/Views/Default/Egitim.cshtml
@using Udemy_MVC_CV.Models.Entity
@model List<TblEgitim>

<div class="resume-section-content">
    <h2 class="mb-5">Eğitim Hayatım</h2>
    @foreach (var item in Model)
    {
        <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="flex-grow-1">
                <h3 class="mb-0">@item.Baslik</h3>
                <div class="subheading mb-3">@item.AltBaslik1</div>
                <div>@item.AltBaslik2</div>
                <p>GNO : @item.GNO</p>
            </div>
            <div class="flex-shrink-0"><span class="text-primary">@item.Tarih</span></div>
        </div>
    }
</div>

Udemy_MVC_CV/Views/Default/Hobilerim.cshtml
@using Udemy_MVC_CV.Models.Entity
@model List<TblHobilerim>
<div class="resume-section-content">
    @foreach (var item in Model)
    {
        <h2 class="mb-5">Hobilerim</h2>
        <p>@item.Aciklama1</p>
        <p class="mb-0">@item.Aciklama2</p>
    }
</div>

Udemy_MVC_CV/Views/Default/Index.cshtml
@using Udemy_MVC_CV.Models.Entity
@model List<TblHakkinda>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>M.Baran Bilal / Portfolyo</title>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/startbootstrap-resume-gh-pages/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">Mahfuz Baran Bilal</span>
            <span class="d-none d-lg-block"><img class="img-fluid img-profile mt-auto mb-2" src="/startbootstrap-resume-gh-pages/assets/img/fOtO.jpg" alt=""   /></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">Hakkımda</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Deneyimlerim</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education">Eğitim Hayatım</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#skills">Yeteneklerim</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#interests">Hobilerim</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#awards">Ödüllerim & Sertifikalarım</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">İletişim</a></li>
            </ul>
        </div>
    </nav>
    <!-- Page Content-->
    <div class="container-fluid p-0">
        <!-- About-->
        @foreach (var item in Model)
        {
            <section class="resume-section" id="about">
                <div class="resume-section-content">
                    <h1 class="mb-0">
                        @item.Ad
                        <span class="text-primary">@item.Soyad</span>
                    </h1>
                    <div class="subheading mb-5">
                        @item.Adres  /  @item.Telefon  /
                        <a href="">@item.Mail</a>
                        @* @Html.Action("Deneyim","Default")*@
                    </div>
                    <p class="lead mb-5">@item.Aciklama</p>
                    <div class="social-icons">
                        <a class="social-icon" href="https://www.linkedin.com/in/mahfuz-baran-bilal-5a3b26285/"><i class="fab fa-linkedin-in"></i></a>
                        <a class="social-icon" href="https://github.com/MBaranBilal"><i class="fab fa-github"></i></a>
                    </div>
                </div>
            </section>
        }
        <hr class="m-0" />
        <!-- Experience-->
        <section class="resume-section" id="experience">
            @Html.Action("Deneyim", "Default")
        </section>
        <hr class="m-0" />
        <!-- Education-->
        <section class="resume-section" id="education">
            @Html.Action("Egitim", "Default")
        </section>
        <hr class="m-0" />
        <!-- Skills-->
        <section class="resume-section" id="skills">
            @Html.Action("Yeteneklerim", "Default")
        </section>
        <hr class="m-0" />
        <!-- Interests-->
        <section class="resume-section" id="interests">
            @Html.Action("Hobilerim", "Default")
        </section>
        <hr class="m-0" />
        <!-- Awards-->
        <section class="resume-section" id="awards">
            @Html.Action("Sertifikalarım", "Default")
        </section>
        <!-- İletişim-->
        <hr class="m-0" />
        <section class="resume-section" id="contact">
            @Html.Action("iletisim", "Default")
        </section>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <script src="/startbootstrap-resume-gh-pages/js/scripts.js"></script>
</body>
</html>

Udemy_MVC_CV/Views/Default/Sertifikalarım.cshtml
@using Udemy_MVC_CV.Models.Entity
@model List<TblSertifikalarim>
<div class="resume-section-content">
    <h2 class="mb-5">Ödüllerim & Sertifikalarım</h2>
    <ul class="fa-ul mb-0">
        @foreach (var item in Model)
        {
            <li>
                <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                @item.Aciklama
            </li>
        }

    </ul>
</div>

Udemy_MVC_CV/Views/Default/Yeteneklerim.cshtml
@using Udemy_MVC_CV.Models.Entity
@model List<TblYetenek>
<div class="resume-section-content">
    <h2 class="mb-5">Yeteneklerim</h2>
    <div class="subheading mb-3">Programlama Dilleri ve Araçlar</div>
    <ul class="list-inline dev-icons">
        <li class="list-inline-item"><i class="fab fa-windows"></i></li>
        <li class="list-inline-item"><i class="fab fa-css3-alt"></i></li>
        <li class="list-inline-item"><i class="fab fa-js-square"></i></li>
        <li class="list-inline-item"><i class="fab fa-angular"></i></li>
        <li class="list-inline-item"><i class="fab fa-java"></i></li>
        <li class="list-inline-item"><i class="fas fa-database"></i></li>
    </ul>
    <div class="subheading mb-3">Becerilerim</div>
    <ul class="fa-ul mb-0">
        @foreach (var item in Model)
        {
            <li>
                <span class="fa-li"><i class="fas fa-check"></i></span>
                @item.Yetenek
            </li>

        }
    </ul>
</div>

Udemy_MVC_CV/Views/Default/iletisim.cshtml
<div class="resume-section-content">
    <form method="post">
        <h2 class="mb-5">İletişim</h2>
        <label>Ad Soyad</label>
        <input type="text" class="form-control" name="AdSoyad" />

        <label>Mail</label>
        <input type="text" class="form-control" name="Mail"/>

        <label>Konu</label>
        <input type="text" class="form-control" name="Konu"/>

        <label>Mesaj</label>
        <input type="text" class="form-control" name="Mesaj"/>

        <br />

        <button class="btn btn-warning">Mesaj Gönder</button>
    </form>
</div>